# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gj2KPNbwKcRBtJUXhLbKMSGvvgOGrTmj
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(33)
torch.manual_seed(33)

def sensation_simulator(features):
    protein, fat, sugar, salt, water = features.T

    # 甜度
    sweetness = 0.9 * sugar + 0.1 * fat
    # 嚼勁：由蛋白質和水分決定 (蛋白質多且水少 = 硬)
    chewiness = 0.8 * protein - 0.2 * water + 0.1
    # 多汁感
    juiciness = 0.5 * fat + 0.5 * water

    # 堆疊成 (N, 3) 的矩陣
    return np.column_stack((sweetness, chewiness, juiciness))

n_samples = 1000
X_np = np.random.rand(n_samples, 5) # 5種化學成分
y_true = sensation_simulator(X_np)  # 3種真實口感

y_noisy = y_true + np.random.normal(0, 0.03, size=y_true.shape)

X_train = torch.FloatTensor(X_np)
y_train = torch.FloatTensor(y_noisy)

class SensoryNet(nn.Module):
    def __init__(self):
        super(SensoryNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(5, 64),
            nn.ReLU(),          # 非線性轉換
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 3)    # 輸出層變成 3 (同時預測 3 種口感)
        )

    def forward(self, x):
        return self.net(x)

model = SensoryNet()
optimizer = optim.Adam(model.parameters(), lr=0.01)
criterion = nn.MSELoss() # 衡量 3 種口感預測的總誤差

print("AI 正在學習化學成分與口感之間的映射...")
losses = []
for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train)
    loss.backward()
    optimizer.step()
    losses.append(loss.item())

plt.figure(figsize=(15, 10))

plt.subplot(2, 2, 1)
plt.plot(losses, color='purple', linewidth=1.5)
plt.title('Training Loss (Learning Efficiency)', fontsize=12, fontweight='bold')
plt.xlabel('Epochs')
plt.ylabel('MSE Loss')
plt.grid(True, alpha=0.3)

sample_range = range(50)
true_data = y_noisy[sample_range]
pred_data = y_final_pred[sample_range]

# --- 子圖 2: 甜度 (Sweetness) - Index 0 ---
plt.subplot(2, 2, 2)
plt.plot(true_data[:, 0], 'ko-', label='True (Brain Signal)', alpha=0.3)
plt.plot(pred_data[:, 0], 'r--', label='AI Simulated', linewidth=2) # 紅色代表甜
plt.title('Sensation 1: Sweetness (Sugar + Fat)', fontsize=12)
plt.xlabel('Sample ID')
plt.ylabel('Intensity')
plt.legend()

# --- 子圖 3: 嚼勁 (Chewiness) - Index 1 ---
plt.subplot(2, 2, 3)
plt.plot(true_data[:, 1], 'ko-', label='True (Brain Signal)', alpha=0.3)
plt.plot(pred_data[:, 1], 'g--', label='AI Simulated', linewidth=2) # 綠色代表嚼勁
plt.title('Sensation 2: Chewiness (Protein - Water)', fontsize=12)
plt.xlabel('Sample ID')
plt.ylabel('Intensity')
plt.legend()

# --- 子圖 4: 多汁感 (Juiciness) - Index 2 ---
plt.subplot(2, 2, 4)
plt.plot(true_data[:, 2], 'ko-', label='True (Brain Signal)', alpha=0.3)
plt.plot(pred_data[:, 2], 'b--', label='AI Simulated', linewidth=2) # 藍色代表多汁
plt.title('Sensation 3: Juiciness (Fat + Water)', fontsize=12)
plt.xlabel('Sample ID')
plt.ylabel('Intensity')
plt.legend()

plt.tight_layout()
plt.savefig('vr_sensation_full_result.png')
plt.show()